### ISSUE TITLE
No Response

### ISSUE THREAD

**Issue by treyaferguson** [pjestico/MMM-GoogleTrafficTimes#1]
I have updated to the latest commit, entered the Google API key, and entered the zip codes for locations. However, nothing at all is populating on my MagicMirror display. Please see my attached config file and MagicMirror screen.

  {
			module: "MMM-GoogleTrafficTimes",
			position: "top_right",
			config: {
				key: "MyAPIKey",
				origin: "92025",
				destination1: "Home:92592",
			}
		},

![CaptureGit](https://user-images.githubusercontent.com/65884558/83315578-cdbc5800-a1d5-11ea-9495-f0cf27a26278.PNG)

**Comment by pjestico** [comment]
Thanks for reporting, I'll see if can recreate with the info you have supplied and provide an update

**Comment by pjestico** [comment]
Just tested your config and it works fine for me.
Displays a single response bubble on the top right showing a travel time of 50 minutes.

I am assuming at this stage that your API key may be the issue.
Can you start MagicMirror with "npm start dev" as opposed to "npm start" and look in the debug window (on the right on my machine) for any errors coming from this module, I would expect it to emit something about a missing Google capability.
If you aren't sure about the log then leave MagicMirror running in dev mode for about 5 minutes and please then submit the log file here.
You can then go back to standard running.

Thank you

Peter

**Comment by treyaferguson** [comment]
Hey Peter,
I looked in to this issue more and still cannot seem to locate the issue.
The Module doesn't appear in my MagicMirror at all. I have included a file
with my Log after following your instructions as well as some of the errors
I found running "npm start dev".
Thanks for your help,

[image: image.png]

**Comment by pjestico** [comment]
Unfortunately there doesn't appear to be any log here.
Could you please try attaching to this issue again?

**Comment by closingin** [comment]
I can confirm that nothing happens on my end either. The error I have is `InvalidValueError: in property destinations: at index 0: not a string; and not a LatLng or LatLngLiteral: not an Object; and not an Object`. Maybe an API change ?

**Comment by pjestico** [comment]
@closingin can you please submit the section of config file you are using for this module please?
@treyaferguson could you supply the requested log info via the website if you are still experiencing issues? Looks like it doesn't come through if attached to mail.

**Comment by pjestico** [comment]
I have just setup a new machine with a fresh OS, installed MagicMirror and this module and added a basic config in order to be sure there are no issues with the code here.
I can confirm this has worked fine as you can hopefully see from the attached screen shot.
If you could supply the requested info I can hopefully work out whats wrong for each of your setups, I suspect its something in your config file or API key setup.
Its likely I could make the README clearer as a result.

![image](https://user-images.githubusercontent.com/22499361/84175582-15fe3480-aa78-11ea-9718-5987ba970357.png)

**Comment by treyaferguson** [comment]
> Unfortunately there doesn't appear to be any log here.
> Could you please try attaching to this issue again?

Attached is the Log file

[2020-06-03T00_40_05_862Z-debug (1).log](https://github.com/pjestico/MMM-GoogleTrafficTimes/files/4755568/2020-06-03T00_40_05_862Z-debug.1.log)

**Comment by pjestico** [comment]
No further update from either responder.
Code validated on another fresh install and no issues so not an issue with that.
At least one of the two reported issues looks like it was a problem with the way the config had been setup so the README file has been updated to try and make things much clearer.
