### ISSUE TITLE
Other countries than UK?

### ISSUE THREAD

**Issue by requiemmg** [pjestico/MMM-GoogleTrafficTimes#2]
Hi,

ZIP/Postcodes rely on UK data only as far as I understand.
Any way to use this in Germany?

**Comment by pjestico** [comment]
Making this work outside f the US and UK is definitely a must.
The issue isn't with Google its with the likelihood that the label matching in the module wont work the way I have it currently implemented.
Let me take a look over the next couple of days and see if I can sort and put out a new release.

**Comment by pjestico** [comment]
Just done a quick test using some addresses across Berlin and Frankfurt and it worked fine
I would suggest go ahead and please update here if you see any failures.
I will look at whether I can make the matching more robust to guarantee success.

**Comment by svrcek** [comment]
Hi,
many thanks for a nice add-on. 
I quickly check the code and your script works even with Plus Codes (like 8QQ7+V8, Dublin) showed by Google Maps for every location. However, I needed  to replace if (destinationList[j].match(re1)) in your MMM-GoogleTrafficTimes.js with another condition (like if (j == 0)) to show the results. You may consider to debug the name comparison condition.

**Comment by pjestico** [comment]
@svrcek Thanks so much for that.
Would you mind attaching your full updated MMM file so I can do some side by side testing and get a new release out?
Release suitably credited with your update of course 😃

**Comment by svrcek** [comment]
The updated file is attached. It could be further optimized for a dynamic destination list support.  

config.js file supports specific addresses (e.g. Plus codes):
		{
			module: "MMM-GoogleTrafficTimes",
			position: "top_left",
			config: {
				key: "xxxxxx",
				origin: "3QGX+Q4 Xuân Đỉnh, Bac Tu Liem, Hanoi, Vietnam",
				destination1: "Work:2QJM+C4 Dịch Vọng Hậu, Cầu Giấy, Hanoi, Vietnam",
				destination2: "Tay Ho:3R7H+H5 Quảng An, Tây Hồ, Hanoi, Vietnam",
				destination3: "Golf:XW3Q+C2 Ecopark Township, Xuân Quan, Văn Giang, Hung Yen, Vietnam",
			 }
		}, 

[MMM-GoogleTrafficTimes.js.zip](https://github.com/pjestico/MMM-GoogleTrafficTimes/files/4917227/MMM-GoogleTrafficTimes.js.zip)

**Comment by pjestico** [comment]
Updated code with suggestion from @svrcek and now pushed as latest release
